### ISSUE TITLE
Allow configuration of the downloading address of dynamodb .tar.gz?

### ISSUE THREAD

**Issue by rosun82** [crewjam/fakeaws#1]
Hi,

We are using fakeaws in China, and found it extremely helpful. However, one issue is that due to some well known yet stupid reasons the downloading of the .tar.gz file is very slow and we would like to switch to an mirror.

If the owner of the package agrees, I would like to make some backward compatible changes. What do you think?

Thanks

--Yi

**Comment by crewjam** [comment]
Sounds reasonable -- please feel free to submit a PR.
